export const ADD = 'ADD'

export const REMOVE = 'REMOVE'

export const CLEARCART = 'CLEARCART'

export const REQUEST_PRODUCTS = 'REQUEST_PRODUCTS'

export const UPDATE_SCROLL = 'UPDATE_SCROLL'

export const UPDATE_SCROLL_ACTIVENAV = 'UPDATE_SCROLL_ACTIVENAV'

export const ASYNC_INCREMENT = 'ASYNC_INCREMENT'